language: ruby
rvm:
  - 2.1.5
  - 2.2.0
  - 2.3.1
gemfile:
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_4.2.3.gemfile
notifications:
  email: false
sudo: false
